### ISSUE TITLE
MemoryError in mean reciprocal rank computation for Brightkite data

### ISSUE THREAD

**Issue by dionman** [flaviovdf/tribeflow#5]
Running the script for reciprocal rank computation on the predictions of the model for the brightkite dataset, I am getting MemoryError upon the creation of predictions array

```
PYTHONPATH=. python scripts/mrr.py data/output_brightkite.h5 rss.dat data/predictions_brightkite.dat &

matrix shape :  (10000, 3) (10000, 1) (525267, 10)
Traceback (most recent call last):
  File "scripts/mrr.py", line 86, in <module>
    plac.call(main)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "scripts/mrr.py", line 77, in main
    HSDs, previous_stamps, Theta_zh, Psi_sz, count_z, kernel, True)
  File "tribeflow/_eval.pyx", line 97, in tribeflow._eval.reciprocal_rank (tribeflow/_eval.c:2525)
    np.zeros(shape=(HOs.shape[0], ns), dtype='d')
MemoryError
```

Is there a  scipy.sparse based workaround for large datasets?

**Comment by flaviovdf** [comment]
No there is not. A lot of the code is in cython and there are no sparse
matrices for that.

--
Flavio
